name: Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create google-services.json
      uses: jsdaniell/create-json@v1.2.2
      with:
          name: "app/src/google-services.json"
          json: ${{ secrets.FIREBASE_JSON }}
          
      # uses: cschleiden/replace-tokens@v1
      # with:
      #     files: 'app/src/google-services.json'
      # env:
      #     SECRET_TOKEN: ${{ secrets.FIREBASE_JSON }}

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.1.1'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
